default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: gyotan_development


test:
  <<: *default
  database: gyotan_test

production:
  adapter: postgresql
  encoding: utf8
  database: gyotan_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000