default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /var/lib/mysql/mysql.sock
  host: localhost

development:
  <<: *default
  database: gyotan_development

test:
  <<: *default
  database: gyotan_test

production:
  <<: *default
  database: gyotan_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock